url: "" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
title: "Po-Ya Wang" # the name of your site, e.g. ACME Corp.
description: "Academmic personal webpage"
timezone: Asia/Taipei
future: true