menu:
- {name: 'publications', url: '/publications'}
# - {name: 'courses', url: '/courses'}
- {name: 'astroph-logs', url: '/astroph-logs'}
- {name: 'cv', url: '/cv'}
- {name: 'contact', url: '/contact'}

# courses:
# - {name: 'Vector Calculus', url: 'vector-calculus'}
# - {name: 'Quantum Mechanics', url: 'quantum-mechanics'}
# - {name: 'Stellar Structures', url: 'stellar-structures'}

# social:
# - {icon: 'github', link: 'https://github.com/LeNPaul'}
# - {icon: 'twitter', link: 'https://twitter.com/paululele'}

contacts:
- {name: 'Po-Ya Wang', title: 'Research Assitant', department: 'Institute of Astronomy', institution: 'National Tsing Hua University', image: 'assets/img/graduate_pic.jpg', email: "poyawang@gapp.nthu.edu.tw"}
